name: Deploy Theme The Geek Writer
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace Hyvor Comments
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "HYVOR_TALK_WEBSITE_CODE"
          replace: ${{ secrets.THE_GEEK_WRITER_HYVOR_WEBSITE_KEY }}
          regex: false
      - name: Find and Replace Adsense Code
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "GOOGLE_ADSENSE_IDENTIFICATION"
          replace: ${{ secrets.GOOGLE_ADSENSE_IDENTIFICATION }}
          regex: false
      - uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.THE_GEEK_WRITER_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.THE_GEEK_WRITER_GHOST_ADMIN_API_KEY }}
          theme-name: "headline-by-oren"
